spring:
  application:
    name: ai-lama-spring
  autoconfigure:
    exclude:
      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:1b
      embedding:
        model: nomic-embed-text

    google:
      genai:
        api-key: ${GOOGLE_GEMINI_API_KEY:}
        model: gemini-2.0-flash

    vectorstore:
      qdrant:
        host: localhost
        port: 6334              # gRPC порт (быстрее чем REST)
        collection-name: knowledge  # имя коллекции в Qdrant
        initialize-schema: true     # автоматически создать коллекцию

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: "${spring.application.name}"

server:
  port: 8888